# Generated by Django 5.2.1 on 2025-08-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_alter_evidence_contribution_submittedcontribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for this contribution type', max_length=100, null=True, unique=True),
        ),
    ]
