# Generated by Django 5.2 on 2025-08-06 16:00

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """
    Populate slug field for existing ContributionType instances.
    """
    ContributionType = apps.get_model('contributions', 'ContributionType')
    
    for contribution_type in ContributionType.objects.all():
        if not contribution_type.slug:
            # Generate slug from name
            base_slug = slugify(contribution_type.name)
            slug = base_slug
            counter = 1
            
            # Ensure uniqueness
            while ContributionType.objects.filter(slug=slug).exclude(id=contribution_type.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            contribution_type.slug = slug
            contribution_type.save()


def reverse_populate_slugs(apps, schema_editor):
    """
    Clear slug field for all ContributionType instances.
    """
    ContributionType = apps.get_model('contributions', 'ContributionType')
    ContributionType.objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_contributiontype_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]