# Generated by Django 5.2.1 on 2025-08-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetNodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(help_text='Target node version (e.g., 1.2.3)', max_length=100)),
                ('target_date', models.DateTimeField(help_text='Date by which validators should upgrade')),
                ('is_active', models.BooleanField(default=True, help_text='Only one target can be active at a time')),
            ],
            options={
                'verbose_name': 'Target Node Version',
                'verbose_name_plural': 'Target Node Versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
